# I do not have a custom configuration for this one so LOL
- name: Install Neovim
  apt: 
    name: neovim
    state: present
  tags:
  - editor
# I kinda do have a custom configuration for this one.
- name: Install VS code 
  apt: 
    name: code
    state: present
  tags:
  - editor

