- name: Install fish
  apt:
    name: fish
    state: present
  tags:
    - fish

- name: Change shell to fish for sankalpmukim
  user:
    name: sankalpmukim
    shell: /usr/bin/fish
  tags:
    - fish

- name: Install fisher (Fish plugin manager tool)
  shell: |
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
  args:
    executable: /usr/bin/fish
  tags:
    - fish

- name: Install nvm for fish
  shell: |
    fisher install jorgebucaran/nvm.fish
  args:
    executable: /usr/bin/fish
  tags:
    - fish
